// Local Host
### Get all certificates
GET http://localhost:3000/certificates

### Get certificate by ID
GET http://localhost:3000/certificates/679744fb0d0a4a1a069a9a34
### Create certificate
POST http://localhost:3000/certificates HTTP/1.1
content-Type: application/json 

{
    "title": "Web Development",
    "outcomes": [
        "Learn the basics of web development",
        "Demonstrate skills in HTML, CSS, Javascript, databases, and server-side development using PHP or .NETNode",
        "Write operational code to pass and obtain data from a server including PHP and JavaScript",
        "Inject data into the DOM (document object model) for dynamic web site applications",
        "Show skill with database servers (Relational and NoSQL) and tools to design and build basic databases needed for dynamic web applications",
        "Demonstrate proficiency in SQL code to implement a CRUD (Create, Read, Update, and Delete) management tool using a web interface",
        "Use code to solve problems"
    ],
    "employment": [
        "General programmer",
        "Web developer"
    ],
    "requirements": "This is an advanced certificate. Prior to working on this certificate, you must complete Web and Computer Programming.",
    "status": "In Progress",
    "credits": 15,
    "courses": [
        "Introduction to Databases",
        "Web Frontend Development II",
        "Web Backend Development",
        "Web Services",
        "Web Full-Stack Development"
    ]
}
### PUT certificate
PUT  http://localhost:3000/certificates/679744fb0d0a4a1a069a9a34
Content-Type: application/json

{
    "title": "Web Development",
    "outcomes": [
        "Learn the basics of web development",
        "Demonstrate skills in HTML, CSS, Javascript, databases, and server-side development using PHP or .NETNode",
        "Write operational code to pass and obtain data from a server including PHP and JavaScript",
        "Inject data into the DOM (document object model) for dynamic web site applications",
        "Show skill with database servers (Relational and NoSQL) and tools to design and build basic databases needed for dynamic web applications",
        "Demonstrate proficiency in SQL code to implement a CRUD (Create, Read, Update, and Delete) management tool using a web interface",
        "Use code to solve problems"
    ],
    "employment": [
        "General programmer",
        "Web developer"
    ],
    "requirements": "This is an advanced certificate. Prior to working on this certificate, you must complete Web and Computer Programming.",
    "status": "In Progress",
    "credits": 15,
    "courses": [
        "Introduction to Databases",
        "Web Frontend Development II",
        "Web Backend Development",
        "Web Services",
        "Web Full-Stack Development"
    ]
}

### Delete certificate
DELETE http://localhost:3000/certificates/679744fb0d0a4a1a069a9a34

//Production
### Get all certificates
GET cse341-purplecre.onrender.com/certificates

### Get certificate by ID
GET cse341-purplecre.onrender.com/certificates/66fd3e0ac8809d867c7576b7

### Create certificate
POST cse341-purplecre.onrender.com/certificates HTTP/1.1
content-Type: application/json 
{
    "title": "Web Development",
    "outcomes": [
        "Learn the basics of web development",
        "Demonstrate skills in HTML, CSS, Javascript, databases, and server-side development using PHP or .NETNode",
        "Write operational code to pass and obtain data from a server including PHP and JavaScript",
        "Inject data into the DOM (document object model) for dynamic web site applications",
        "Show skill with database servers (Relational and NoSQL) and tools to design and build basic databases needed for dynamic web applications",
        "Demonstrate proficiency in SQL code to implement a CRUD (Create, Read, Update, and Delete) management tool using a web interface",
        "Use code to solve problems"
    ],
    "employment": [
        "General programmer",
        "Web developer"
    ],
    "requirements": "This is an advanced certificate. Prior to working on this certificate, you must complete Web and Computer Programming.",
    "status": "In Progress",
    "credits": 15,
    "courses": [
        "Introduction to Databases",
        "Web Frontend Development II",
        "Web Backend Development",
        "Web Services",
        "Web Full-Stack Development"
    ]
}

### PUT certificate
PUT  cse341-purplecre.onrender.com/certificates/66fd3e0ac8809d867c7576b7 HTTP/1.1
Content-Type: application/json
{
    "title": "Web Development",
    "outcomes": [
        "Learn the basics of web development",
        "Demonstrate skills in HTML, CSS, Javascript, databases, and server-side development using PHP or .NETNode",
        "Write operational code to pass and obtain data from a server including PHP and JavaScript",
        "Inject data into the DOM (document object model) for dynamic web site applications",
        "Show skill with database servers (Relational and NoSQL) and tools to design and build basic databases needed for dynamic web applications",
        "Demonstrate proficiency in SQL code to implement a CRUD (Create, Read, Update, and Delete) management tool using a web interface",
        "Use code to solve problems"
    ],
    "employment": [
        "General programmer",
        "Web developer"
    ],
    "requirements": "This is an advanced certificate. Prior to working on this certificate, you must complete Web and Computer Programming.",
    "status": "In Progress",
    "credits": 15,
    "courses": [
        "Introduction to Databases",
        "Web Frontend Development II",
        "Web Backend Development",
        "Web Services",
        "Web Full-Stack Development"
    ]
}

### Delete certificate
DELETE cse341-purplecre.onrender.com/certificates/670ab5a90ffefe4c9fe41522